#pragma once
#include <iostream>
#include <string>
#include <cstdio>
#include <vector>
#include <algorithm>
#include <typeinfo>
#include <math.h>
#include <ctime>
#include <fstream>
#include <sstream>
#include <stdlib.h>
#include <chrono>
#include <random>
#include <iomanip>
#include <numeric>
#include <iterator>
#include <list>

using std::vector;
using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::sort;
using std::to_string;
using std::generate;
using std::ifstream;
using std::stringstream;
using std::remove_if;
using std::exception;
using std::chrono::high_resolution_clock;
using std::mt19937;
using std::uniform_int_distribution;
using std::ofstream;
using std::setw;
using std::left;
using std::right;
using std::chrono::duration;
using std::accumulate;
using std::istream_iterator;
using std::list;
using std::ws;
using std::remove_copy_if;
using std::istream;
using std::swap;
